POST http://localhost:3000/api/hero HTTP/1.1
Content-Type: application/json 

{
  "nickname": "Valera",
  "realName": "Pupkin",
  "originDescription": "He Strange",
  "catchPhrase": "ive above them.",
  "superPowers":["fly","jump","bite"]
}